@startuml Gerenciamento de Exames Medicos

    class Paciente{
        - nome : String
        - idade : Integer
        - CPF : Integer
        + construtor(nome, idade, cpf)
        + marcarConsulta(Especialidade, dia, hora)
        + getNome()
        + getIdade()
        + getCPF()
    }

    class CadastroPaciente{
        - cpf : integer
    }

    class Medico{
        - nome : String
        - idade : Integer
        - CRM : Integer
        + construtor(nome, idade, crm)
        + getNome()
        + getIdade()
        + getCRM()
    }

    class Especialidade{
        - nome : String
        + construtor(nome)
        + getNome()
    }

    class Clinica{
        - nome : String
        - endereco : String
        - telefone : Integer
        + construtor(nome, endereco, telefone)
        + getNome()
        + getEndereco()
        + getTelefone()
    }

    class Sala{
        - numeroSala : Integer
        - andar : Integer
        + construtor(numeroSala, andar)
    }

    Paciente *-- Medico
    Paciente *-- Especialidade

    Clinica *-- Sala

@enduml