@startuml Gerenciamento de Exames Medicos

    class Agenda{
        - hora : String
        - sala : Sala
        - exame : Exames
        + construtor(hora, sala, exame)
    }

    class Paciente{
        - nome : String
        - idade : Integer
        + construtor(nome, idade, cpf)
        + marcarConsulta(Especialidade, dia, hora)
        + getNome()
        + getIdade()
    }

    class CadastroPaciente{
        - cpf : Integer
        - endereco : String
        - telefone : Integer
        - paciente : Paciente
        + construtor(cpf, endereco, telefone, paciente)
    }

    class Medico{
        - nome : String
        - idade : Integer
        - CRM : Integer
        - paciente : Paciente
        + construtor(nome, idade, crm, paciente)
        + getNome()
        + getIdade()
        + getCRM()
    }

    class Exames{
        - nome : String
        - tipoExame : String
        + construtor(nome, tipoExame)
    }

    class Especialidade{
        - nome : String
        - medico : Medico
        + construtor(nome, medico)
        + getNome()
    }

    class Clinica{
        - nome : String
        - endereco : String
        - telefone : Integer
        + construtor(nome, endereco, telefone)
        + getNome()
        + getEndereco()
        + getTelefone()
    }

    class Sala{
        - numeroSala : Integer
        - andar : Integer
        + construtor(numeroSala, andar)
    }

    Paciente <|-- CadastroPaciente
    Paciente <|-- Medico
    Medico *-- Especialidade

    Clinica *-- Sala

@enduml